// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjuz4_KmLRWBq5OVRKhT6pYbylrY4PUkg',
    appId: '1:793223636897:web:7de9f378215e45b0cd8de0',
    messagingSenderId: '793223636897',
    projectId: 'mathlab-research',
    authDomain: 'mathlab-research.firebaseapp.com',
    storageBucket: 'mathlab-research.appspot.com',
    measurementId: 'G-7JKBQM7096',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu9x7krhZo5oZPYLNllZHlzF4nbu5ndQ8',
    appId: '1:793223636897:android:e225f484a46597d2cd8de0',
    messagingSenderId: '793223636897',
    projectId: 'mathlab-research',
    storageBucket: 'mathlab-research.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeVSukzchY3o4YpBGzejNlORHSinyemD0',
    appId: '1:793223636897:ios:fca6027f9abbe5f4cd8de0',
    messagingSenderId: '793223636897',
    projectId: 'mathlab-research',
    storageBucket: 'mathlab-research.appspot.com',
    iosClientId: '793223636897-r9t65p0v1ma25lams5dd6hp9ku6dhd4l.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathlab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeVSukzchY3o4YpBGzejNlORHSinyemD0',
    appId: '1:793223636897:ios:62bf31c3f65a387dcd8de0',
    messagingSenderId: '793223636897',
    projectId: 'mathlab-research',
    storageBucket: 'mathlab-research.appspot.com',
    iosClientId: '793223636897-0hh8nm6mjsconba67km9elhf0peeu3c0.apps.googleusercontent.com',
    iosBundleId: 'com.example.mathlab.RunnerTests',
  );
}
